[mypy]
python_version = 3.11
namespace_packages = True
ignore_missing_imports = True
warn_unused_ignores = False
warn_return_any = False
check_untyped_defs = False
disallow_untyped_defs = False

[mypy-tests.*]
ignore_errors = True
