"""create users table

Revision ID: 3e059b69cd69
Revises: 
Create Date: 2026-06-19 20:54:50.019582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '3e059b69cd69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), server_default=sa.text("''"), nullable=False),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=True)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('new_word_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), server_default=sa.text("'generator'"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_stories_level'), 'stories', ['level'], unique=False)
    op.create_index('ix_stories_level_created_at', 'stories', ['level', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('native_language', sa.String(length=16), nullable=True),
    sa.Column('target_language', sa.String(length=16), nullable=True),
    sa.Column('cefr_goal', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(email) >= 3', name='ck_users_email_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_words_lemma'), 'words', ['lemma'], unique=False)
    op.create_index(op.f('ix_words_level'), 'words', ['level'], unique=False)
    op.create_index('ix_words_level_rank', 'words', ['level', 'rank'], unique=False)
    op.create_index(op.f('ix_words_rank'), 'words', ['rank'], unique=True)
    op.create_table('classroom_grants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assigned_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'student_id', name='uq_classroom_teacher_student')
    )
    op.create_index(op.f('ix_classroom_grants_student_id'), 'classroom_grants', ['student_id'], unique=False)
    op.create_index(op.f('ix_classroom_grants_teacher_id'), 'classroom_grants', ['teacher_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=32), server_default=sa.text("'file'"), nullable=False),
    sa.Column('title', sa.String(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('term_freqs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'content_hash', name='uq_knowledge_chunk_content_hash')
    )
    op.create_index(op.f('ix_knowledge_chunks_content_hash'), 'knowledge_chunks', ['content_hash'], unique=False)
    op.create_index('ix_knowledge_chunks_kb_source', 'knowledge_chunks', ['knowledge_base_id', 'source'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_id'), 'knowledge_chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source'), 'knowledge_chunks', ['source'], unique=False)
    op.create_table('partner_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('daily_prompt_hour_utc', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_type', 'external_id', name='uq_partner_channel')
    )
    op.create_index(op.f('ix_partner_channels_user_id'), 'partner_channels', ['user_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('source_type', sa.String(length=32), server_default=sa.text("'upload'"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_organization_id'), 'rag_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_project_id'), 'rag_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_user_id'), 'rag_documents', ['user_id'], unique=False)
    op.create_table('rag_queries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('retrieved_chunk_ids_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_name', sa.String(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_queries_project_id'), 'rag_queries', ['project_id'], unique=False)
    op.create_index(op.f('ix_rag_queries_user_id'), 'rag_queries', ['user_id'], unique=False)
    op.create_table('story_words',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('story_id', 'word_id', name='uq_story_words_story_word')
    )
    op.create_index(op.f('ix_story_words_story_id'), 'story_words', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_words_word_id'), 'story_words', ['word_id'], unique=False)
    op.create_table('tutor_chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.String(length=64), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('language', sa.String(length=8), server_default=sa.text("'en'"), nullable=False),
    sa.Column('cefr_level', sa.String(length=8), nullable=True),
    sa.Column('persona', sa.String(length=64), nullable=True),
    sa.Column('last_turn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_tutor_user_session')
    )
    op.create_index(op.f('ix_tutor_chat_sessions_session_id'), 'tutor_chat_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_tutor_chat_sessions_user_id'), 'tutor_chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_tutor_sessions_user_last_turn', 'tutor_chat_sessions', ['user_id', 'last_turn_at'], unique=False)
    op.create_table('tutor_chat_turns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('parent_turn_id', sa.String(length=64), nullable=True),
    sa.Column('seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'running'"), nullable=False),
    sa.Column('capability', sa.String(length=64), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('language', sa.String(length=8), server_default=sa.text("'en'"), nullable=False),
    sa.Column('cefr_level', sa.String(length=8), nullable=True),
    sa.Column('persona', sa.String(length=64), nullable=True),
    sa.Column('user_message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assistant_reply', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pause_question', sa.Text(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tutor_chat_turns_parent_turn_id'), 'tutor_chat_turns', ['parent_turn_id'], unique=False)
    op.create_index(op.f('ix_tutor_chat_turns_session_id'), 'tutor_chat_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_tutor_chat_turns_turn_id'), 'tutor_chat_turns', ['turn_id'], unique=True)
    op.create_index(op.f('ix_tutor_chat_turns_user_id'), 'tutor_chat_turns', ['user_id'], unique=False)
    op.create_index('ix_tutor_turns_session_created', 'tutor_chat_turns', ['session_id', 'created_at'], unique=False)
    op.create_table('user_lesson_page_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'page_id', name='uq_user_lesson_page')
    )
    op.create_index(op.f('ix_user_lesson_page_progress_level'), 'user_lesson_page_progress', ['level'], unique=False)
    op.create_index(op.f('ix_user_lesson_page_progress_page_id'), 'user_lesson_page_progress', ['page_id'], unique=False)
    op.create_index(op.f('ix_user_lesson_page_progress_user_id'), 'user_lesson_page_progress', ['user_id'], unique=False)
    op.create_table('user_mastery_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('progress_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'level', name='uq_user_mastery_level')
    )
    op.create_index(op.f('ix_user_mastery_progress_level'), 'user_mastery_progress', ['level'], unique=False)
    op.create_index(op.f('ix_user_mastery_progress_user_id'), 'user_mastery_progress', ['user_id'], unique=False)
    op.create_table('user_memory_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.String(length=8), nullable=False),
    sa.Column('doc_key', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'layer', 'doc_key', name='uq_user_memory_doc')
    )
    op.create_index('ix_user_memory_documents_lookup', 'user_memory_documents', ['user_id', 'layer', 'doc_key'], unique=False)
    op.create_index(op.f('ix_user_memory_documents_user_id'), 'user_memory_documents', ['user_id'], unique=False)
    op.create_table('user_memory_traces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_traces_kind'), 'user_memory_traces', ['kind'], unique=False)
    op.create_index(op.f('ix_user_memory_traces_surface'), 'user_memory_traces', ['surface'], unique=False)
    op.create_index(op.f('ix_user_memory_traces_user_id'), 'user_memory_traces', ['user_id'], unique=False)
    op.create_index('ix_user_memory_traces_user_surface', 'user_memory_traces', ['user_id', 'surface'], unique=False)
    op.create_table('user_word_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('recognition_strength', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('recall_strength', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('production_strength', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ease_factor', sa.Float(), server_default=sa.text('2.5'), nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_progress')
    )
    op.create_index('ix_user_word_progress_review', 'user_word_progress', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_word_progress_word_id'), 'user_word_progress', ['word_id'], unique=False)
    op.create_table('word_forms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('form', sa.String(length=128), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_form'), 'word_forms', ['form'], unique=False)
    op.create_index(op.f('ix_word_forms_word_id'), 'word_forms', ['word_id'], unique=False)
    op.create_table('word_notebook_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('context', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'lemma', name='uq_word_notebook_user_lemma')
    )
    op.create_index(op.f('ix_word_notebook_entries_lemma'), 'word_notebook_entries', ['lemma'], unique=False)
    op.create_index(op.f('ix_word_notebook_entries_user_id'), 'word_notebook_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_word_notebook_entries_word_id'), 'word_notebook_entries', ['word_id'], unique=False)
    op.create_index('ix_word_notebook_user_created', 'word_notebook_entries', ['user_id', 'created_at'], unique=False)
    op.create_table('partner_message_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.String(length=4000), server_default=sa.text("''"), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['partner_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_message_logs_channel_id'), 'partner_message_logs', ['channel_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('vector_external_id', sa.String(length=128), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_chunks_doc_index', 'rag_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_organization_id'), 'rag_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_project_id'), 'rag_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_user_id'), 'rag_chunks', ['user_id'], unique=False)
    op.create_index('ix_rag_chunks_user_project', 'rag_chunks', ['user_id', 'project_id'], unique=False)
    op.create_table('rag_ingestion_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_ingestion_jobs_document_id'), 'rag_ingestion_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_ingestion_jobs_user_id'), 'rag_ingestion_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_ingestion_jobs_user_id'), table_name='rag_ingestion_jobs')
    op.drop_index(op.f('ix_rag_ingestion_jobs_document_id'), table_name='rag_ingestion_jobs')
    op.drop_table('rag_ingestion_jobs')
    op.drop_index('ix_rag_chunks_user_project', table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_user_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_project_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_organization_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_doc_index', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_partner_message_logs_channel_id'), table_name='partner_message_logs')
    op.drop_table('partner_message_logs')
    op.drop_index('ix_word_notebook_user_created', table_name='word_notebook_entries')
    op.drop_index(op.f('ix_word_notebook_entries_word_id'), table_name='word_notebook_entries')
    op.drop_index(op.f('ix_word_notebook_entries_user_id'), table_name='word_notebook_entries')
    op.drop_index(op.f('ix_word_notebook_entries_lemma'), table_name='word_notebook_entries')
    op.drop_table('word_notebook_entries')
    op.drop_index(op.f('ix_word_forms_word_id'), table_name='word_forms')
    op.drop_index(op.f('ix_word_forms_form'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index(op.f('ix_user_word_progress_word_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_index('ix_user_word_progress_review', table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_index('ix_user_memory_traces_user_surface', table_name='user_memory_traces')
    op.drop_index(op.f('ix_user_memory_traces_user_id'), table_name='user_memory_traces')
    op.drop_index(op.f('ix_user_memory_traces_surface'), table_name='user_memory_traces')
    op.drop_index(op.f('ix_user_memory_traces_kind'), table_name='user_memory_traces')
    op.drop_table('user_memory_traces')
    op.drop_index(op.f('ix_user_memory_documents_user_id'), table_name='user_memory_documents')
    op.drop_index('ix_user_memory_documents_lookup', table_name='user_memory_documents')
    op.drop_table('user_memory_documents')
    op.drop_index(op.f('ix_user_mastery_progress_user_id'), table_name='user_mastery_progress')
    op.drop_index(op.f('ix_user_mastery_progress_level'), table_name='user_mastery_progress')
    op.drop_table('user_mastery_progress')
    op.drop_index(op.f('ix_user_lesson_page_progress_user_id'), table_name='user_lesson_page_progress')
    op.drop_index(op.f('ix_user_lesson_page_progress_page_id'), table_name='user_lesson_page_progress')
    op.drop_index(op.f('ix_user_lesson_page_progress_level'), table_name='user_lesson_page_progress')
    op.drop_table('user_lesson_page_progress')
    op.drop_index('ix_tutor_turns_session_created', table_name='tutor_chat_turns')
    op.drop_index(op.f('ix_tutor_chat_turns_user_id'), table_name='tutor_chat_turns')
    op.drop_index(op.f('ix_tutor_chat_turns_turn_id'), table_name='tutor_chat_turns')
    op.drop_index(op.f('ix_tutor_chat_turns_session_id'), table_name='tutor_chat_turns')
    op.drop_index(op.f('ix_tutor_chat_turns_parent_turn_id'), table_name='tutor_chat_turns')
    op.drop_table('tutor_chat_turns')
    op.drop_index('ix_tutor_sessions_user_last_turn', table_name='tutor_chat_sessions')
    op.drop_index(op.f('ix_tutor_chat_sessions_user_id'), table_name='tutor_chat_sessions')
    op.drop_index(op.f('ix_tutor_chat_sessions_session_id'), table_name='tutor_chat_sessions')
    op.drop_table('tutor_chat_sessions')
    op.drop_index(op.f('ix_story_words_word_id'), table_name='story_words')
    op.drop_index(op.f('ix_story_words_story_id'), table_name='story_words')
    op.drop_table('story_words')
    op.drop_index(op.f('ix_rag_queries_user_id'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_project_id'), table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index(op.f('ix_rag_documents_user_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_project_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_organization_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_partner_channels_user_id'), table_name='partner_channels')
    op.drop_table('partner_channels')
    op.drop_index(op.f('ix_knowledge_chunks_source'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_kb_source', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_content_hash'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_classroom_grants_teacher_id'), table_name='classroom_grants')
    op.drop_index(op.f('ix_classroom_grants_student_id'), table_name='classroom_grants')
    op.drop_table('classroom_grants')
    op.drop_index(op.f('ix_words_rank'), table_name='words')
    op.drop_index('ix_words_level_rank', table_name='words')
    op.drop_index(op.f('ix_words_level'), table_name='words')
    op.drop_index(op.f('ix_words_lemma'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_stories_level_created_at', table_name='stories')
    op.drop_index(op.f('ix_stories_level'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
