from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

# Source type semantics:
# - "rss": `url` is a concrete RSS/Atom URL that your fetcher can read directly.
# - "rss_page": `url` is a page that lists RSS feeds; resolve the exact feed before fetching.
# - "public_page": `url` is a normal website/category page; do not scrape until ToS/robots/use rights are reviewed.
# - "generated": fallback source for AI-generated educational texts without an external article.
SourceType = Literal["rss", "rss_page", "public_page", "generated"]
Country = Literal["NL", "BE", "NL/BE", ""]
UseMode = Literal[
    "rss_summary",
    "source_facts",
    "facts_and_link_only",
    "full_text_if_allowed",
    "generated",
]


@dataclass(frozen=True)
class SourceDefinition:
    name: str
    type: SourceType
    url: str
    publisher: str = ""
    website_url: str = ""
    category_url: str = ""
    rss_url: str = ""
    country: Country = ""
    language: str = "nl"
    use_mode: UseMode = "facts_and_link_only"
    requires_attribution: bool = True
    commercial_use_check_required: bool = True
    notes: str = ""


SOURCE_REGISTRY: dict[str, list[SourceDefinition]] = {
    'news': [
        SourceDefinition(
            name='NOS',
            type='rss',
            url='https://feeds.nos.nl/nosnieuwsalgemeen',
            publisher='NOS',
            website_url='https://nos.nl',
            category_url='https://nos.nl/nieuws',
            rss_url='https://feeds.nos.nl/nosnieuwsalgemeen',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='General Dutch news. Good v1 source.',
        ),
        SourceDefinition(
            name='VRT NWS',
            type='public_page',
            url='https://www.vrt.be/vrtnws/nl/',
            publisher='VRT',
            website_url='https://www.vrt.be/vrtnws/nl/',
            category_url='https://www.vrt.be/vrtnws/nl/',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Flemish public news. Manually verify content-use terms before automated crawling.',
        ),
        SourceDefinition(
            name='NU.nl',
            type='rss',
            url='https://www.nu.nl/rss/Algemeen',
            publisher='NU.nl',
            website_url='https://www.nu.nl',
            category_url='https://www.nu.nl',
            rss_url='https://www.nu.nl/rss/Algemeen',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Popular Dutch news site. Use RSS summaries and attribution.',
        ),
        SourceDefinition(
            name='De Standaard',
            type='rss_page',
            url='https://www.standaard.be/extra/rss-feeds/49064508.html',
            publisher='De Standaard',
            website_url='https://www.standaard.be',
            category_url='https://www.standaard.be',
            rss_url='https://www.standaard.be/extra/rss-feeds/49064508.html',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial newspaper; some content may be metered/paywalled.',
        ),
        SourceDefinition(
            name='HLN',
            type='public_page',
            url='https://www.hln.be',
            publisher='HLN',
            website_url='https://www.hln.be',
            category_url='https://www.hln.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial news site; manual ToS/robots review required.',
        ),
        SourceDefinition(
            name='BRUZZ',
            type='public_page',
            url='https://www.bruzz.be',
            publisher='BRUZZ',
            website_url='https://www.bruzz.be',
            category_url='https://www.bruzz.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Brussels news and culture; manual ToS/robots review required.',
        ),
    ],
    'sports': [
        SourceDefinition(
            name='NOS Sport',
            type='rss',
            url='https://feeds.nos.nl/nossportalgemeen',
            publisher='NOS',
            website_url='https://nos.nl',
            category_url='https://nos.nl/sport',
            rss_url='https://feeds.nos.nl/nossportalgemeen',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Good v1 sports source.',
        ),
        SourceDefinition(
            name='Sporza',
            type='public_page',
            url='https://sporza.be',
            publisher='VRT',
            website_url='https://sporza.be',
            category_url='https://sporza.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Major Flemish sports source; VRT terms apply.',
        ),
        SourceDefinition(
            name='Sportnieuws.nl',
            type='rss_page',
            url='https://sportnieuws.nl/page/rss/',
            publisher='Sportnieuws.nl',
            website_url='https://sportnieuws.nl',
            category_url='https://sportnieuws.nl',
            rss_url='https://sportnieuws.nl/page/rss/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='RSS page available; resolve exact feed before production.',
        ),
        SourceDefinition(
            name='KNVB',
            type='rss',
            url='https://www.knvb.nl/rss-feed-knvb',
            publisher='KNVB',
            website_url='https://www.knvb.nl',
            category_url='https://www.knvb.nl/nieuws',
            rss_url='https://www.knvb.nl/rss-feed-knvb',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Official Dutch football association news.',
        ),
        SourceDefinition(
            name='Voetbal International',
            type='rss_page',
            url='https://www.vi.nl/pagina/rss-feeds',
            publisher='Voetbal International',
            website_url='https://www.vi.nl',
            category_url='https://www.vi.nl',
            rss_url='https://www.vi.nl/pagina/rss-feeds',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial sports publisher; manual content-use review required.',
        ),
        SourceDefinition(
            name='Voetbalnieuws',
            type='rss_page',
            url='https://www.voetbalnieuws.nl/pagina/rss-feeds',
            publisher='Voetbalnieuws',
            website_url='https://www.voetbalnieuws.nl',
            category_url='https://www.voetbalnieuws.nl',
            rss_url='https://www.voetbalnieuws.nl/pagina/rss-feeds',
            country='NL/BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Football news; manual content-use review required.',
        ),
    ],
    'technology': [
        SourceDefinition(
            name='Tweakers',
            type='rss',
            url='https://tweakers.net/feeds/mixed.xml',
            publisher='Tweakers',
            website_url='https://tweakers.net',
            category_url='https://tweakers.net/nieuws/',
            rss_url='https://tweakers.net/feeds/mixed.xml',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Strong Dutch technology source. Check terms before full-text reuse.',
        ),
        SourceDefinition(
            name='Bright',
            type='rss_page',
            url='https://www.bright.nl/pagina/rss-feeds',
            publisher='Bright',
            website_url='https://www.bright.nl',
            category_url='https://www.bright.nl',
            rss_url='https://www.bright.nl/pagina/rss-feeds',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Technology/lifestyle source with RSS page.',
        ),
        SourceDefinition(
            name='iCulture',
            type='rss',
            url='https://www.iculture.nl/feed/',
            publisher='iCulture',
            website_url='https://www.iculture.nl',
            category_url='https://www.iculture.nl',
            rss_url='https://www.iculture.nl/feed/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Apple/iOS focused Dutch tech source.',
        ),
        SourceDefinition(
            name='Techzine',
            type='rss',
            url='https://www.techzine.nl/feed/',
            publisher='Techzine',
            website_url='https://www.techzine.nl',
            category_url='https://www.techzine.nl',
            rss_url='https://www.techzine.nl/feed/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Business technology source.',
        ),
        SourceDefinition(
            name='Data News',
            type='public_page',
            url='https://datanews.knack.be',
            publisher='Data News',
            website_url='https://datanews.knack.be',
            category_url='https://datanews.knack.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian technology source; manual ToS/robots review required.',
        ),
        SourceDefinition(
            name='VRT NWS Tech',
            type='public_page',
            url='https://www.vrt.be/vrtnws/nl/tags/tech/',
            publisher='VRT',
            website_url='https://www.vrt.be/vrtnws/nl/',
            category_url='https://www.vrt.be/vrtnws/nl/tags/tech/',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Flemish public news technology tag; VRT terms apply.',
        ),
    ],
    'science': [
        SourceDefinition(
            name='NEMO Kennislink',
            type='public_page',
            url='https://www.nemokennislink.nl',
            publisher='NEMO Kennislink',
            website_url='https://www.nemokennislink.nl',
            category_url='https://www.nemokennislink.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Educational science source; manual content-use review required.',
        ),
        SourceDefinition(
            name='Scientias',
            type='rss_page',
            url='https://scientias.nl/rss-feeds/',
            publisher='Scientias',
            website_url='https://scientias.nl',
            category_url='https://scientias.nl',
            rss_url='https://scientias.nl/rss-feeds/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Science articles with topic feed page.',
        ),
        SourceDefinition(
            name='RIVM',
            type='rss',
            url='https://www.rivm.nl/en/rss-news',
            publisher='RIVM',
            website_url='https://www.rivm.nl',
            category_url='https://www.rivm.nl',
            rss_url='https://www.rivm.nl/en/rss-news',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Reliable public-health/science source.',
        ),
        SourceDefinition(
            name='CBS',
            type='rss_page',
            url='https://www.cbs.nl/nl-nl/rss-feeds',
            publisher='CBS',
            website_url='https://www.cbs.nl/nl-nl',
            category_url='https://www.cbs.nl/nl-nl',
            rss_url='https://www.cbs.nl/nl-nl/rss-feeds',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official statistics source; good for facts and educational texts.',
        ),
        SourceDefinition(
            name='EOS Wetenschap',
            type='public_page',
            url='https://www.eoswetenschap.eu',
            publisher='EOS Wetenschap',
            website_url='https://www.eoswetenschap.eu',
            category_url='https://www.eoswetenschap.eu',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian/Flemish science magazine; manual content-use review required.',
        ),
        SourceDefinition(
            name='NPO Kennis',
            type='public_page',
            url='https://npokennis.nl',
            publisher='NPO',
            website_url='https://npokennis.nl',
            category_url='https://npokennis.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Educational public-media explanations; verify reuse before crawling.',
        ),
    ],
    'business': [
        SourceDefinition(
            name='CBS Economie',
            type='rss_page',
            url='https://www.cbs.nl/nl-nl/rss-feeds',
            publisher='CBS',
            website_url='https://www.cbs.nl/nl-nl',
            category_url='https://www.cbs.nl/nl-nl/economie',
            rss_url='https://www.cbs.nl/nl-nl/rss-feeds',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official economy/statistics source.',
        ),
        SourceDefinition(
            name='DNB',
            type='rss_page',
            url='https://www.dnb.nl/en/rss/',
            publisher='De Nederlandsche Bank',
            website_url='https://www.dnb.nl',
            category_url='https://www.dnb.nl',
            rss_url='https://www.dnb.nl/en/rss/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Central bank/economy source.',
        ),
        SourceDefinition(
            name='Rijksoverheid Economie',
            type='rss_page',
            url='https://www.rijksoverheid.nl/rss',
            publisher='Rijksoverheid',
            website_url='https://www.rijksoverheid.nl',
            category_url='https://www.rijksoverheid.nl/onderwerpen/economie',
            rss_url='https://www.rijksoverheid.nl/rss',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official government economy topics.',
        ),
        SourceDefinition(
            name='Ondernemersplein',
            type='public_page',
            url='https://www.ondernemersplein.nl',
            publisher='Rijksoverheid / KvK / RVO',
            website_url='https://www.ondernemersplein.nl',
            category_url='https://www.ondernemersplein.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Business guidance for entrepreneurs; verify reuse.',
        ),
        SourceDefinition(
            name='RVO',
            type='public_page',
            url='https://www.rvo.nl',
            publisher='Rijksdienst voor Ondernemend Nederland',
            website_url='https://www.rvo.nl',
            category_url='https://www.rvo.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official business/subsidy/export information; verify page-specific reuse.',
        ),
        SourceDefinition(
            name='FD',
            type='rss',
            url='https://fd.nl/?rss',
            publisher='Het Financieele Dagblad',
            website_url='https://fd.nl',
            category_url='https://fd.nl',
            rss_url='https://fd.nl/?rss',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial/paywalled business newspaper; do not store/rewrite full articles without permission.',
        ),
        SourceDefinition(
            name='De Tijd',
            type='rss_page',
            url='https://www.tijd.be/rss',
            publisher='De Tijd',
            website_url='https://www.tijd.be',
            category_url='https://www.tijd.be',
            rss_url='https://www.tijd.be/rss',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial/paywalled business newspaper; use summaries/facts and attribution.',
        ),
        SourceDefinition(
            name='Voka',
            type='public_page',
            url='https://www.voka.be/nieuws',
            publisher='Voka',
            website_url='https://www.voka.be',
            category_url='https://www.voka.be/nieuws',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Flemish business network news; manual content-use review required.',
        ),
        SourceDefinition(
            name='Trends',
            type='rss',
            url='https://trends.knack.be/feed/',
            publisher='Trends',
            website_url='https://trends.knack.be',
            category_url='https://trends.knack.be',
            rss_url='https://trends.knack.be/feed/',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Commercial business magazine; manual content-use review required.',
        ),
    ],
    'arts': [
        SourceDefinition(
            name='NOS Cultuur & Media',
            type='rss',
            url='https://feeds.nos.nl/nosnieuwscultuur',
            publisher='NOS',
            website_url='https://nos.nl',
            category_url='https://nos.nl/nieuws/cultuur-en-media',
            rss_url='https://feeds.nos.nl/nosnieuwscultuur',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Good v1 arts/culture news source.',
        ),
        SourceDefinition(
            name='VRT NWS Cultuur',
            type='public_page',
            url='https://www.vrt.be/vrtnws/nl/tags/cultuur/',
            publisher='VRT',
            website_url='https://www.vrt.be/vrtnws/nl/',
            category_url='https://www.vrt.be/vrtnws/nl/tags/cultuur/',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Flemish public culture news; VRT terms apply.',
        ),
        SourceDefinition(
            name='Theaterkrant',
            type='rss',
            url='https://www.theaterkrant.nl/feed/',
            publisher='Theaterkrant',
            website_url='https://www.theaterkrant.nl',
            category_url='https://www.theaterkrant.nl',
            rss_url='https://www.theaterkrant.nl/feed/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Dutch theatre source.',
        ),
        SourceDefinition(
            name='Boekblad',
            type='public_page',
            url='https://www.boekblad.nl',
            publisher='Boekblad',
            website_url='https://www.boekblad.nl',
            category_url='https://www.boekblad.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Book/literary sector news; manual content-use review required.',
        ),
        SourceDefinition(
            name='Cultureelerfgoed.nl',
            type='public_page',
            url='https://www.cultureelerfgoed.nl',
            publisher='Rijksdienst voor het Cultureel Erfgoed',
            website_url='https://www.cultureelerfgoed.nl',
            category_url='https://www.cultureelerfgoed.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official cultural heritage source; verify page-specific reuse.',
        ),
        SourceDefinition(
            name='DBNL',
            type='public_page',
            url='https://www.dbnl.org',
            publisher='DBNL',
            website_url='https://www.dbnl.org',
            category_url='https://www.dbnl.org',
            rss_url='',
            country='NL/BE',
            language='nl',
            use_mode='full_text_if_allowed',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Digital library; check rights per text before full-text use.',
        ),
    ],
    'culture': [
        SourceDefinition(
            name='Canon van Nederland',
            type='public_page',
            url='https://www.canonvannederland.nl',
            publisher='Canon van Nederland',
            website_url='https://www.canonvannederland.nl',
            category_url='https://www.canonvannederland.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Stable educational culture/history content.',
        ),
        SourceDefinition(
            name='DBNL',
            type='public_page',
            url='https://www.dbnl.org',
            publisher='DBNL',
            website_url='https://www.dbnl.org',
            category_url='https://www.dbnl.org',
            rss_url='',
            country='NL/BE',
            language='nl',
            use_mode='full_text_if_allowed',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Check rights per text before full-text use.',
        ),
        SourceDefinition(
            name='NPO Kennis',
            type='public_page',
            url='https://npokennis.nl',
            publisher='NPO',
            website_url='https://npokennis.nl',
            category_url='https://npokennis.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Educational public-media explanations; verify reuse before crawling.',
        ),
        SourceDefinition(
            name='Literatuurgeschiedenis',
            type='public_page',
            url='https://www.literatuurgeschiedenis.org',
            publisher='Literatuurgeschiedenis',
            website_url='https://www.literatuurgeschiedenis.org',
            category_url='https://www.literatuurgeschiedenis.org',
            rss_url='',
            country='NL/BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Educational literature-history source; manual content-use review required.',
        ),
        SourceDefinition(
            name='VRT NWS Cultuur',
            type='public_page',
            url='https://www.vrt.be/vrtnws/nl/tags/cultuur/',
            publisher='VRT',
            website_url='https://www.vrt.be/vrtnws/nl/',
            category_url='https://www.vrt.be/vrtnws/nl/tags/cultuur/',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Flemish public culture news; VRT terms apply.',
        ),
    ],
    'travel': [
        SourceDefinition(
            name='ANWB Reizen',
            type='public_page',
            url='https://www.anwb.nl/vakantie',
            publisher='ANWB',
            website_url='https://www.anwb.nl',
            category_url='https://www.anwb.nl/vakantie',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Travel/practical guidance; manual content-use review required.',
        ),
        SourceDefinition(
            name='Nederland Wereldwijd Reizen',
            type='public_page',
            url='https://www.nederlandwereldwijd.nl/reizen',
            publisher='Nederland Wereldwijd',
            website_url='https://www.nederlandwereldwijd.nl',
            category_url='https://www.nederlandwereldwijd.nl/reizen',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official travel information; verify page-specific reuse.',
        ),
        SourceDefinition(
            name='Visit Flanders',
            type='public_page',
            url='https://www.visitflanders.com/nl',
            publisher='Visit Flanders',
            website_url='https://www.visitflanders.com/nl',
            category_url='https://www.visitflanders.com/nl',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official tourism source; manual content-use review required.',
        ),
        SourceDefinition(
            name='Reisjunk',
            type='rss',
            url='https://www.reisjunk.nl/feed/',
            publisher='Reisjunk',
            website_url='https://www.reisjunk.nl',
            category_url='https://www.reisjunk.nl',
            rss_url='https://www.reisjunk.nl/feed/',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Travel blog; check commercial reuse terms.',
        ),
        SourceDefinition(
            name='Columbus Travel',
            type='public_page',
            url='https://www.columbusmagazine.nl',
            publisher='Columbus Travel',
            website_url='https://www.columbusmagazine.nl',
            category_url='https://www.columbusmagazine.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Travel magazine; manual content-use review required.',
        ),
        SourceDefinition(
            name='The Orange Backpack',
            type='rss',
            url='https://theorangebackpack.nl/feed/',
            publisher='The Orange Backpack',
            website_url='https://theorangebackpack.nl',
            category_url='https://theorangebackpack.nl',
            rss_url='https://theorangebackpack.nl/feed/',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Travel blog; check commercial reuse terms.',
        ),
    ],
    'health': [
        SourceDefinition(
            name='Thuisarts',
            type='public_page',
            url='https://www.thuisarts.nl',
            publisher='Thuisarts',
            website_url='https://www.thuisarts.nl',
            category_url='https://www.thuisarts.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Reliable Dutch health information; do not present generated output as medical advice.',
        ),
        SourceDefinition(
            name='RIVM Gezondheid',
            type='rss',
            url='https://www.rivm.nl/en/rss-news',
            publisher='RIVM',
            website_url='https://www.rivm.nl',
            category_url='https://www.rivm.nl',
            rss_url='https://www.rivm.nl/en/rss-news',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Reliable public-health source.',
        ),
        SourceDefinition(
            name='Gezondheidsraad',
            type='rss_page',
            url='https://www.gezondheidsraad.nl/service/rss',
            publisher='Gezondheidsraad',
            website_url='https://www.gezondheidsraad.nl',
            category_url='https://www.gezondheidsraad.nl',
            rss_url='https://www.gezondheidsraad.nl/service/rss',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official health advisory source.',
        ),
        SourceDefinition(
            name='Gezondheid.be',
            type='public_page',
            url='https://www.gezondheid.be',
            publisher='Gezondheid.be',
            website_url='https://www.gezondheid.be',
            category_url='https://www.gezondheid.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian health information; manual content-use review required.',
        ),
        SourceDefinition(
            name='Domus Medica',
            type='public_page',
            url='https://www.domusmedica.be',
            publisher='Domus Medica',
            website_url='https://www.domusmedica.be',
            category_url='https://www.domusmedica.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian medical/professional source; manual content-use review required.',
        ),
        SourceDefinition(
            name='NPO Kennis Gezondheid',
            type='public_page',
            url='https://npokennis.nl/thema/gezondheid-voeding',
            publisher='NPO',
            website_url='https://npokennis.nl',
            category_url='https://npokennis.nl/thema/gezondheid-voeding',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Educational health/food explanations; verify reuse before crawling.',
        ),
    ],
    'environment': [
        SourceDefinition(
            name='PBL',
            type='rss_page',
            url='https://www.pbl.nl/rss-feeds',
            publisher='Planbureau voor de Leefomgeving',
            website_url='https://www.pbl.nl',
            category_url='https://www.pbl.nl',
            rss_url='https://www.pbl.nl/rss-feeds',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official environment/planning source.',
        ),
        SourceDefinition(
            name='RIVM Milieu',
            type='rss',
            url='https://www.rivm.nl/en/rss-news',
            publisher='RIVM',
            website_url='https://www.rivm.nl',
            category_url='https://www.rivm.nl',
            rss_url='https://www.rivm.nl/en/rss-news',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Reliable public environment/health source.',
        ),
        SourceDefinition(
            name='Milieu Centraal',
            type='public_page',
            url='https://www.milieucentraal.nl',
            publisher='Milieu Centraal',
            website_url='https://www.milieucentraal.nl',
            category_url='https://www.milieucentraal.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Practical environment/daily-life guidance; manual content-use review required.',
        ),
        SourceDefinition(
            name='Duurzaam Ondernemen',
            type='rss_page',
            url='https://www.duurzaam-ondernemen.nl/rss-feeds/',
            publisher='Duurzaam Ondernemen',
            website_url='https://www.duurzaam-ondernemen.nl',
            category_url='https://www.duurzaam-ondernemen.nl',
            rss_url='https://www.duurzaam-ondernemen.nl/rss-feeds/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Sustainability/business news with RSS page.',
        ),
        SourceDefinition(
            name='VMM',
            type='public_page',
            url='https://www.vmm.be',
            publisher='Vlaamse Milieumaatschappij',
            website_url='https://www.vmm.be',
            category_url='https://www.vmm.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official Flemish environment source; verify page-specific reuse.',
        ),
        SourceDefinition(
            name='Bond Beter Leefmilieu',
            type='public_page',
            url='https://www.bondbeterleefmilieu.be',
            publisher='Bond Beter Leefmilieu',
            website_url='https://www.bondbeterleefmilieu.be',
            category_url='https://www.bondbeterleefmilieu.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Environmental NGO source; manual content-use review required.',
        ),
    ],
    'history': [
        SourceDefinition(
            name='Historiek',
            type='rss_page',
            url='https://historiek.net/historieknet-via-rss/',
            publisher='Historiek',
            website_url='https://historiek.net',
            category_url='https://historiek.net',
            rss_url='https://historiek.net/historieknet-via-rss/',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='History articles with RSS page; good v1 history source.',
        ),
        SourceDefinition(
            name='IsGeschiedenis',
            type='rss_page',
            url='https://isgeschiedenis.nl/feed-pagina',
            publisher='IsGeschiedenis',
            website_url='https://isgeschiedenis.nl',
            category_url='https://isgeschiedenis.nl',
            rss_url='https://isgeschiedenis.nl/feed-pagina',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='History articles with feed page.',
        ),
        SourceDefinition(
            name='Canon van Nederland',
            type='public_page',
            url='https://www.canonvannederland.nl',
            publisher='Canon van Nederland',
            website_url='https://www.canonvannederland.nl',
            category_url='https://www.canonvannederland.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Stable educational history content.',
        ),
        SourceDefinition(
            name='DBNL',
            type='public_page',
            url='https://www.dbnl.org',
            publisher='DBNL',
            website_url='https://www.dbnl.org',
            category_url='https://www.dbnl.org',
            rss_url='',
            country='NL/BE',
            language='nl',
            use_mode='full_text_if_allowed',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Digital library; check rights per text before full-text use.',
        ),
        SourceDefinition(
            name='Nationaal Archief',
            type='public_page',
            url='https://www.nationaalarchief.nl',
            publisher='Nationaal Archief',
            website_url='https://www.nationaalarchief.nl',
            category_url='https://www.nationaalarchief.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official archival/history source; verify page-specific reuse.',
        ),
        SourceDefinition(
            name='War Heritage Institute',
            type='public_page',
            url='https://www.warheritage.be',
            publisher='War Heritage Institute',
            website_url='https://www.warheritage.be',
            category_url='https://www.warheritage.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian war/history heritage source; manual content-use review required.',
        ),
    ],
    'daily_life': [
        SourceDefinition(
            name='Rijksoverheid',
            type='rss_page',
            url='https://www.rijksoverheid.nl/rss',
            publisher='Rijksoverheid',
            website_url='https://www.rijksoverheid.nl',
            category_url='https://www.rijksoverheid.nl',
            rss_url='https://www.rijksoverheid.nl/rss',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Official daily-life/government topics.',
        ),
        SourceDefinition(
            name='Nibud',
            type='public_page',
            url='https://www.nibud.nl',
            publisher='Nibud',
            website_url='https://www.nibud.nl',
            category_url='https://www.nibud.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Personal finance/daily-life guidance; manual content-use review required.',
        ),
        SourceDefinition(
            name='Milieu Centraal',
            type='public_page',
            url='https://www.milieucentraal.nl',
            publisher='Milieu Centraal',
            website_url='https://www.milieucentraal.nl',
            category_url='https://www.milieucentraal.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Practical sustainability/daily-life guidance.',
        ),
        SourceDefinition(
            name='Radar',
            type='rss',
            url='https://radar.avrotros.nl/rss',
            publisher='AVROTROS Radar',
            website_url='https://radar.avrotros.nl',
            category_url='https://radar.avrotros.nl',
            rss_url='https://radar.avrotros.nl/rss',
            country='NL',
            language='nl',
            use_mode='rss_summary',
            requires_attribution=True,
            commercial_use_check_required=False,
            notes='Consumer daily-life topics.',
        ),
        SourceDefinition(
            name='Consumentenbond',
            type='public_page',
            url='https://www.consumentenbond.nl',
            publisher='Consumentenbond',
            website_url='https://www.consumentenbond.nl',
            category_url='https://www.consumentenbond.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Consumer advice; commercial/member content may be restricted.',
        ),
        SourceDefinition(
            name='Testaankoop',
            type='public_page',
            url='https://www.test-aankoop.be',
            publisher='Testaankoop',
            website_url='https://www.test-aankoop.be',
            category_url='https://www.test-aankoop.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Belgian consumer advice; manual content-use review required.',
        ),
        SourceDefinition(
            name='Libelle NL',
            type='public_page',
            url='https://www.libelle.nl',
            publisher='Libelle',
            website_url='https://www.libelle.nl',
            category_url='https://www.libelle.nl',
            rss_url='',
            country='NL',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Lifestyle source; manual content-use review required.',
        ),
        SourceDefinition(
            name='Libelle BE',
            type='public_page',
            url='https://www.libelle.be',
            publisher='Libelle',
            website_url='https://www.libelle.be',
            category_url='https://www.libelle.be',
            rss_url='',
            country='BE',
            language='nl',
            use_mode='facts_and_link_only',
            requires_attribution=True,
            commercial_use_check_required=True,
            notes='Lifestyle source; manual content-use review required.',
        ),
    ],
}


GENERATED_FALLBACK_SOURCE = SourceDefinition(
    name="AI Generated Educational Text",
    type="generated",
    url="generated://frequency-based-reading",
    publisher="Internal",
    website_url="",
    category_url="",
    rss_url="",
    country="",
    language="nl",
    use_mode="generated",
    requires_attribution=False,
    commercial_use_check_required=False,
    notes="Use only when external source fetching fails or when the user selects generated mode.",
)


def get_sources_for_interest(interest_area: str) -> list[SourceDefinition]:
    """Return a copy of configured sources for an interest area, falling back to news.

    Returning a copy prevents callers from accidentally mutating the global
    SOURCE_REGISTRY when they sort/shuffle/filter sources.
    """
    return list(SOURCE_REGISTRY.get(interest_area, SOURCE_REGISTRY["news"]))


def get_direct_rss_sources_for_interest(interest_area: str) -> list[SourceDefinition]:
    """Return only concrete RSS/Atom sources that can be fetched directly.

    rss_page and public_page entries are intentionally excluded; they need
    feed-resolution and/or Terms/robots review before automated crawling.
    """
    return [
        source
        for source in get_sources_for_interest(interest_area)
        if source.type == "rss" and source.rss_url and source.url == source.rss_url
    ]


def get_review_required_sources_for_interest(interest_area: str) -> list[SourceDefinition]:
    """Return sources requiring manual Terms/robots/licensing review before crawling."""
    return [
        source
        for source in get_sources_for_interest(interest_area)
        if source.commercial_use_check_required or source.type in {"rss_page", "public_page"}
    ]